{{- if .Values.rbac.enabled }}
{{- range $namespace := .Values.rbac.namespaces }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keel-role-{{ $namespace }}
  # name: "keel-role:{{ $namespace.name }}"
  namespace: {{ $namespace }}
rules:
- apiGroups:
      - ""
  resources:
    - secrets
  verbs:
    - get
    - watch
    - list
- apiGroups:
    - ""
    - extensions
    - apps
    - batch
  resources:
    - pods
    - replicasets
    - replicationcontrollers
    - statefulsets
    - deployments
    - daemonsets
    - jobs
    - cronjobs
  verbs:
    - get
    - delete # required to delete pods during force upgrade of the same tag
    - watch
    - list
    - update
- apiGroups:
    - ""
  resources:
    - configmaps
    - pods/portforward
  verbs:
    - get
    - create
    - update
  {{- end }}
{{- end }}
