{{- if .Values.rbac.enabled }}
{{- range $namespace := .Values.rbac.namespaces }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keel-rolebinding-{{ $namespace }}
  namespace: {{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keel-role-{{ $namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ template "serviceAccount.name" . }}
    namespace: {{ .Release.Namespace }} # the service account lives in keel's namespace (presumably)
{{- end}}
{{- end}}
